service_name: "go-common"

s3_endpoint: "http://127.0.0.1:9000"
s3_region: "cn-east-1"
s3_access_key: "minioadmin"
s3_secret_key: "minioadmin123"
s3_bucket: "msss-test"
s3_use_ssl: false
s3_force_path_style: true
s3_base_prefix: "uploads"
s3_public: false
s3_sign_expire_seconds: 600
